# Generated by Django 3.2.8 on 2021-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectnote',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
