# Generated by Django 3.2.8 on 2021-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_subjectnote_file_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectnote',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='subjectnote',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
